[project]
name = "audio-server"
version = "0.1.0"
description = "Transcribe the given audio in a list of filepaths or urls."
readme = "README.md"
requires-python = ">=3.12"
aiohttp= ">=3.12.15"
dependencies = [
    "mcp",
    "requests~=2.32.4",
    "openai~=1.93.0",
    "fastmcp~=2.11.3",
]

