name: AWorld docs deploy

on:
  push:
    branches:
      - docs-main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: aworld-docs
        run: |
          python -m pip install --upgrade pip==25.0.1
          python -m pip install mkdocs mkdocs-material
      - name: Build and deploy
        run: |
          mkdocs build
          mkdocs gh-deploy --force