name: AWorld docs deploy

on:
  push:
    branches:
      - docs-main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==25.0.1
          python -m pip install mkdocs mkdocs-material
      - name: Build and deploy
        working-directory: AWorld
        run: |
          mkdocs build
          mkdocs gh-deploy --force
          rm -rf site